import { type NextPage } from 'next';
import Link from 'next/link';
import { useCallback } from 'react';
import { signIn } from 'next-auth/react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';

import { loginSchema, type ILogin } from '../common/validation/authSchemas';

const Home: NextPage = () => {
  const { handleSubmit, control, reset } = useForm<ILogin>({
    defaultValues: {
      email: '',
      password: '',
    },
    resolver: zodResolver(loginSchema),
  });

  const onSubmit = useCallback(
    async (data: ILogin) => {
      try {
        await signIn('credentials', { ...data, callbackUrl: '/' });
        reset();
      } catch (err) {
        console.error(err);
      }
    },
    [reset]
  );

  return (
    <div>
      {/* <Head>
        <title>Catalog App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="flex justify-center mt-5">
        <div className="bg-white rounded shadow p-4">
          <form onSubmit={(e) => void handleSubmit(onSubmit)(e)}>
            <h2 className="text-xl font-bold mb-4">Welcome back!</h2>
            <div className="mb-4">
              <Controller
                name="email"
                control={control}
                render={({ field }) => (
                  <input
                    type="email"
                    placeholder="Enter your email..."
                    className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
                    {...field}
                  />
                )}
              />
            </div>
            <div className="mb-4">
              <Controller
                name="password"
                control={control}
                render={({ field }) => (
                  <input
                    type="password"
                    placeholder="Enter your password..."
                    className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
                    {...field}
                  />
                )}
              />
            </div>
            <div className="flex justify-center">
              <button className="bg-blue-500 text-white px-4 py-2 rounded-md" type="submit">
                Login
              </button>
            </div>
            <div className="mt-4">
              Not a member?{' '}
              <Link href="/sign-up" className="text-blue-500 underline">
                Register
              </Link>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Home;
