import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback } from "react";
import { signIn } from "next-auth/react";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { loginSchema, ILogin } from "../common/validation/authSchemas";


// The sign in page that shows you the data before the authentication happens
const Home: NextPage = () => {

  const { handleSubmit, control, reset } = useForm<ILogin>({
    defaultValues: {
      email: "",
      password: "",
    },
    resolver: zodResolver(loginSchema),
  });

  const onSubmit = useCallback(
    async (data: ILogin) => {
      try {
        await signIn("credentials", { ...data, callbackUrl: "/" });
        reset();
      } catch (err) {
        console.error(err);
      }
    },
    [reset]
  );

  return (
    <div className="mt-5">
      <Head>
        <title>Catalog App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  >
        <div className="card col-3">
        <form 
          className="d-flex justify-content-center card-body"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="card-body" >
            <div>
              <h2 className="">Welcome back!</h2>
              <div className="form-outline mb-2">
              <Controller
                name="email"
                control={control}
                render={({ field }) => (
                  <input
                    type="email"
                    placeholder="Type your email..."
                    className="form-control"
                    {...field}
                  />
                )}
              />
              </div>
              <div  className="mb-4">
              <Controller
                name="password"
                control={control}
                render={({ field }) => (
                  <input
                    type="password"
                    placeholder="Type your password..."
                    className="form-control"
                    {...field}
                  />
                )}
              />
              </div>
              <div className = "d-flex justify-content-center">
                  <button className="btn btn-primary btn-block mb-4" type="submit">
                    Login
                  </button>
                </div>
                <div>Not a member? <Link href="/sign-up" className="link">Register</Link> </div>
            </div>
          </div>
        </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
