import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback } from "react";
import { signIn } from "next-auth/react";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { loginSchema, ILogin } from "../common/validation/authSchemas";


// The sign in page that shows you the data before the authentication happens
const Home: NextPage = () => {

  const { handleSubmit, control, reset } = useForm<ILogin>({
    defaultValues: {
      email: "",
      password: "",
    },
    resolver: zodResolver(loginSchema),
  });

  const onSubmit = useCallback(
    async (data: ILogin) => {
      try {
        await signIn("credentials", { ...data, callbackUrl: "/" });
        reset();
      } catch (err) {
        console.error(err);
      }
    },
    [reset]
  );

  return (
    <div>
      <Head>
        <title>Catalog App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="d-flex justify-content-center mt-5">
        <div className="card">
          <form
            className="card-body"
            onSubmit={handleSubmit(onSubmit)}
          >
            <div className="card-body">
                <h2 className="card-title">Welcome back!</h2>
                <div className="form-outline mb-2">
                  
                  <Controller
                    name="email"
                    control={control}
                    render={({ field }) => (
                      <input
                        type="email"
                        placeholder="Type your email..."
                        className="form-control"
                        {...field}
                      />
                    )}
                  />

                <div className="mt-2 mb-4">
                  <Controller
                    name="password"
                    control={control}
                    render={({ field }) => (
                      <input
                        type="password"
                        placeholder="Type your password..."
                        className="form-control"
                        {...field}
                      />
                    )}
                  />
                </div>
                <div className="d-flex justify-content-center">
                  <button className="btn btn-primary btn-block mb-4" type="submit">Login</button>
                </div>
                <div>Not a member? <Link href="/sign-up" className="link">Register</Link> </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <style jsx>
        {
          `
          container {
          display: flex;
          justify-content: center;
            }
          `
        }
      </style>
    </div>
  );
};

export default Home;
